/**
 * GET    /api/v1/webhooks — list webhooks for this API key (secret never returned)
 * POST   /api/v1/webhooks — register a new webhook endpoint
 * DELETE /api/v1/webhooks — delete a webhook by id
 */

import { createClient } from "@supabase/supabase-js";
import { NextRequest, NextResponse } from "next/server";
import { validateApiKey } from "@/lib/apiAuth";

function getServiceClient() {
  return createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL!,
    process.env.SUPABASE_SERVICE_ROLE_KEY!
  );
}

function isValidHttpsUrl(input: string): boolean {
  try {
    const u = new URL(input);
    return u.protocol === "https:";
  } catch {
    return false;
  }
}

// GET — list webhooks, secret excluded
export async function GET(req: NextRequest) {
  const apiKey = await validateApiKey(req);
  if (!apiKey) {
    return NextResponse.json({ error: "Invalid API key" }, { status: 401 });
  }

  const supabase = getServiceClient();

  const { data, error } = await supabase
    .from("webhooks")
    .select("id, url, active, created_at")  // secret intentionally omitted
    .eq("api_key_id", apiKey.id)
    .order("created_at", { ascending: false });

  if (error) {
    console.error("[API v1] GET /webhooks error:", error.message);
    return NextResponse.json({ error: "Failed to fetch webhooks" }, { status: 500 });
  }

  return NextResponse.json({ webhooks: data ?? [] });
}

// POST — register webhook, returns secret once
export async function POST(req: NextRequest) {
  const apiKey = await validateApiKey(req);
  if (!apiKey) {
    return NextResponse.json({ error: "Invalid API key" }, { status: 401 });
  }

  let webhookUrl: string;
  try {
    const body = await req.json();
    webhookUrl = typeof body?.url === "string" ? body.url.trim() : "";
  } catch {
    return NextResponse.json({ error: "url is required" }, { status: 400 });
  }

  if (!webhookUrl) {
    return NextResponse.json({ error: "url is required" }, { status: 400 });
  }
  if (!isValidHttpsUrl(webhookUrl)) {
    return NextResponse.json({ error: "url must be a valid https URL" }, { status: 400 });
  }

  const supabase = getServiceClient();

  // secret is auto-generated by the DB default (gen_random_uuid()::text)
  const { data, error } = await supabase
    .from("webhooks")
    .insert({ api_key_id: apiKey.id, url: webhookUrl })
    .select("id, url, secret, created_at")  // secret returned here — only time it's exposed
    .single();

  if (error || !data) {
    console.error("[API v1] POST /webhooks error:", error?.message);
    return NextResponse.json({ error: "Failed to register webhook" }, { status: 500 });
  }

  return NextResponse.json(data, { status: 201 });
}

// DELETE — remove webhook, only if it belongs to this API key
export async function DELETE(req: NextRequest) {
  const apiKey = await validateApiKey(req);
  if (!apiKey) {
    return NextResponse.json({ error: "Invalid API key" }, { status: 401 });
  }

  let webhookId: string;
  try {
    const body = await req.json();
    webhookId = typeof body?.id === "string" ? body.id.trim() : "";
  } catch {
    return NextResponse.json({ error: "id is required" }, { status: 400 });
  }

  if (!webhookId) {
    return NextResponse.json({ error: "id is required" }, { status: 400 });
  }

  const supabase = getServiceClient();

  // Both conditions must match — ownership is enforced at query level
  const { error } = await supabase
    .from("webhooks")
    .delete()
    .eq("id", webhookId)
    .eq("api_key_id", apiKey.id);

  if (error) {
    console.error("[API v1] DELETE /webhooks error:", error.message);
    return NextResponse.json({ error: "Failed to delete webhook" }, { status: 500 });
  }

  return NextResponse.json({ deleted: true });
}
