/**
 * GET /api/scan/status/:reportId — dashboard scan-progress poll.
 *
 * Looks up a report by ITS ROW ID (not share_token — share_token is regenerated by
 * saveReport at completion and is unknown while a scan is in flight). Ownership is
 * enforced: cookie session identifies the user, and the row is fetched scoped to
 * user_id, so another user's id resolves to no row → 404 (never leaks a report).
 *
 * Response:
 *   { status: 'pending' }                                        — scan in progress
 *   { status: 'failed', error }                                  — scan failed
 *   { status: 'complete', share_token, health_score, verdict }   — ready to open
 *
 * This is a pure read used by DashboardShell's ScanProvider to track a scan across
 * dashboard tab navigation. It touches no scan-pipeline logic.
 */

import { createServerClient } from "@supabase/ssr";
import { createClient } from "@supabase/supabase-js";
import { cookies } from "next/headers";
import { NextResponse } from "next/server";

export const maxDuration = 10;

export async function GET(
  _req: Request,
  { params }: { params: Promise<{ reportId: string }> }
) {
  const { reportId } = await params;
  if (!reportId) {
    return NextResponse.json({ error: "reportId is required" }, { status: 400 });
  }

  const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
  const serviceKey = process.env.SUPABASE_SERVICE_ROLE_KEY;
  const anonKey = process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;
  if (!supabaseUrl || !serviceKey || !anonKey) {
    return NextResponse.json({ error: "Server configuration error." }, { status: 500 });
  }

  // Identify the caller from the session cookie (same pattern as /api/profile).
  const cookieStore = await cookies();
  const supabaseAuth = createServerClient(supabaseUrl, anonKey, {
    cookies: {
      getAll() {
        return cookieStore.getAll();
      },
      setAll() {
        /* read-only: this route never refreshes session cookies */
      },
    },
  });

  const {
    data: { user },
  } = await supabaseAuth.auth.getUser();
  if (!user?.id) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  // Service client scoped to (id, user_id) — enforces ownership without relying on RLS
  // session propagation, mirroring how the other authenticated dashboard routes read.
  const supabaseAdmin = createClient(supabaseUrl, serviceKey);
  const { data, error } = await supabaseAdmin
    .from("reports")
    .select("id, status, share_token, health_score, verdict")
    .eq("id", reportId)
    .eq("user_id", user.id)
    .maybeSingle();

  if (error) {
    return NextResponse.json({ error: "Lookup failed." }, { status: 500 });
  }
  if (!data) {
    return NextResponse.json({ error: "Not found" }, { status: 404 });
  }

  const row = data as {
    status: string | null;
    share_token: string | null;
    health_score: number | null;
    verdict: string | null;
  };

  // A freshly-inserted row carries status 'pending' (verdict 'pending', score 0);
  // saveReport flips it to 'complete' in the same write that sets the real token/score.
  if (!row.status || row.status === "pending") {
    return NextResponse.json({ status: "pending" });
  }
  if (row.status === "failed" || row.status === "error") {
    return NextResponse.json({ status: "failed", error: "Scan failed" });
  }

  return NextResponse.json({
    status: "complete",
    share_token: row.share_token ?? null,
    health_score: typeof row.health_score === "number" ? row.health_score : 0,
    verdict: row.verdict ?? null,
  });
}
